### ISSUE TITLE
Error 400: Clusters with minor version 1.18 and basic authentication enabled cannot migrate to rapid, regular or stable release channels. Basic authentication was removed for GKE cluster versions >= 1.19.

### ISSUE THREAD

**Issue by vodelerk** [hashicorp/learn-terraform-pipelines-k8s#5]
im trying to reproduce this tutorial: https://learn.hashicorp.com/tutorials/terraform/kubernetes-consul-vault-pipeline?in=terraform/cloud

when trying to deploy the K8s cluster, I got this error from TFC regarding Google Cloud

Terraform v0.15.3
on linux_amd64
-[0m-[1mgoogle_container_cluster.engineering: Creating...-[0m-[0m
-[31m╷-[0m-[0m
-[31m│-[0m -[0m-[1m-[31mError: -[0m-[0m-[1mgoogleapi: Error 400: Clusters with minor version 1.18 and basic authentication enabled cannot migrate to rapid, regular or stable release channels. Basic authentication was removed for GKE cluster versions >= 1.19. To disable basic authentication use: `gcloud container clusters update %s --no-enable-basic-auth`. Instructions for choosing a new method can be found at: https://cloud.google.com/kubernetes-engine/docs/how-to/api-server-authentication., badRequest-[0m
-[31m│-[0m -[0m
-[31m│-[0m -[0m-[0m  with google_container_cluster.engineering,
-[31m│-[0m -[0m  on gke.tf line 3, in resource "google_container_cluster" "engineering":
-[31m│-[0m -[0m   3: resource "google_container_cluster" "engineering" -[4m{-[0m-[0m
-[31m│-[0m -[0m
-[31m╵-[0m-[0m

any advice?

thank you

**Comment by im2nguyen** [comment]
In [`gke.tf`](https://github.com/hashicorp/learn-terraform-pipelines-k8s/blob/master/gke.tf), can you try removing the `master_auth` block? Please let me know if this works 😄 

```
resource "google_container_cluster" "engineering" {
  name     = var.cluster_name
  location = data.google_compute_zones.available.names.0

  # We can't create a cluster with no node pool defined, but we want to only use
  # separately managed node pools. So we create the smallest possible default
  # node pool and immediately delete it.
  remove_default_node_pool = true
  initial_node_count       = 1

  ip_allocation_policy {}
}
```

**Comment by vodelerk** [comment]
@im2nguyen thank you, it fixed the issue!. but, I have a new one, I'm trying to access the consul UI but when I tried to run this from GC shell: "kubectl port-forward -n hashicorp-learn consul-server-0 8080:8500" , 

I got: Error from server (NotFound): pods "consul-server-0" not found

from TFC all workspaces were deployed successfully, but I don't see any consul-server-0 anywhere (checked system workload, configuration)

any advice on this one?

Thanks in advance,

**Comment by im2nguyen** [comment]
That's awesome! If you want to, you can open a PR for this repo, that way you get to contribute to the repo 😄 otherwise, I can update it haha

Oh, that's interesting. Did you update `kubectl` with your GKE credentials? Replace `PROJECT_NAME` with your project name.

```
$ gcloud container clusters get-credentials tfc-pipelines --zone us-central1-a   --project PROJECT_NAME
```

You can test the connection by trying to retrieve the pods.

```
$ kubectl get pods -n hashicorp-learn
```

**Comment by vodelerk** [comment]
yes, I have previously updated kubectl , just tried this one: kubectl get pods -n hashicorp-learn
and I got this:
No resources found in hashicorp-learn namespace.

**Comment by im2nguyen** [comment]
That's strange... that means Consul and Vault weren't installed. 🤔 

What happens when you try to retrieve nodes?

```
$ kubectl get nodes
```

**Comment by vodelerk** [comment]
kubectl get nodes
NAME                                                  STATUS   ROLES    AGE   VERSION
gke-tfc-pipelines-tfc-pipelines-node--b1ac48a6-gjgw   Ready    <none>   34m   v1.19.9-gke.1400
gke-tfc-pipelines-tfc-pipelines-node--b1ac48a6-h43q   Ready    <none>   30m   v1.19.9-gke.1400
gke-tfc-pipelines-tfc-pipelines-node--b1ac48a6-pzr6   Ready    <none>   34m   v1.19.9-gke.1400
gke-tfc-pipelines-tfc-pipelines-node--b1ac48a6-qgm3   Ready    <none>   34m   v1.19.9-gke.1400
gke-tfc-pipelines-tfc-pipelines-node--b1ac48a6-x2jj   Ready    <none>   29m   v1.19.9-gke.1400

**Comment by im2nguyen** [comment]
That's great, that means it successfully increased the nodes from 3 to 5. 

Do you have the outputs for the Consul and Vault workspaces? Did it confirm that the resources were deployed?

Can you also try going to the [GKE console](https://console.cloud.google.com/kubernetes)? What do you find when you select workloads?

![image](https://user-images.githubusercontent.com/7556325/118921590-4c316e80-b8ed-11eb-807c-29b3460e4257.png)

**Comment by vodelerk** [comment]
the output from consul workspace:

Terraform v0.15.4
on linux_amd64
kubernetes_namespace.secrets[0]: Creating...
kubernetes_namespace.secrets[0]: Creation complete after 0s [id=hashicorp-learn]
helm_release.consul[0]: Creating...
helm_release.consul[0]: Creation complete after 2s [id=hashicorp-learn-consul]

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

Outputs:

namespace = "hashicorp-learn"
release_name = "hashicorp-learn"


the output from vault workspace: 

Terraform v0.15.4
on linux_amd64
helm_release.vault[0]: Creating...
helm_release.vault[0]: Creation complete after 2s [id=hashicorp-learn-vault]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.


![image](https://user-images.githubusercontent.com/17457173/118922101-02ea1a80-b8ff-11eb-950a-b316651e89d7.png)


and if I select hashicorp-learn for namespace, I get nothing

![image](https://user-images.githubusercontent.com/17457173/118922277-5b211c80-b8ff-11eb-81f0-b2c2b7468716.png)

**Comment by im2nguyen** [comment]
That's interesting... I don't know why it doesn't work. Give me a min, going to spin up the environment on my end

**Comment by im2nguyen** [comment]
That's strange... when I try to do it on my end, it works as expected. (the only difference is that I used `tfc-pipelines-test` as the name, since we already had an GKE cluster named `tfc-pipelines`, and only used 3 nodes so I didn't have to wait for node pool to increase)

Can you try queue a destroy on both the Vault and Consul workspaces and re-apply them?

![image](https://user-images.githubusercontent.com/7556325/118926903-e1d0fc00-b8f5-11eb-816b-85fbf5c033dd.png)

**Comment by vodelerk** [comment]
I tried to destroy vault first, but i got this:

Terraform v0.15.4
on linux_amd64
helm_release.vault[0]: Destroying... [id=hashicorp-learn-vault]
╷
│ Error: uninstallation completed with 5 error(s): rolebindings.rbac.authorization.k8s.io "hashicorp-learn-vault-discovery-rolebinding" is forbidden: User "174602363821-compute@developer.gserviceaccount.com" cannot delete resource "rolebindings" in API group "rbac.authorization.k8s.io" in the namespace "hashicorp-learn": requires one of ["container.roleBindings.delete"] permission(s).; roles.rbac.authorization.k8s.io "hashicorp-learn-vault-discovery-role" is forbidden: User "174602363821-compute@developer.gserviceaccount.com" cannot delete resource "roles" in API group "rbac.authorization.k8s.io" in the namespace "hashicorp-learn": requires one of ["container.roles.delete"] permission(s).; clusterrolebindings.rbac.authorization.k8s.io "hashicorp-learn-vault-agent-injector-binding" is forbidden: User "174602363821-compute@developer.gserviceaccount.com" cannot delete resource "clusterrolebindings" in API group "rbac.authorization.k8s.io" at the cluster scope: requires one of ["container.clusterRoleBindings.delete"] permission(s).; clusterrolebindings.rbac.authorization.k8s.io "hashicorp-learn-vault-server-binding" is forbidden: User "174602363821-compute@developer.gserviceaccount.com" cannot delete resource "clusterrolebindings" in API group "rbac.authorization.k8s.io" at the cluster scope: requires one of ["container.clusterRoleBindings.delete"] permission(s).; clusterroles.rbac.authorization.k8s.io "hashicorp-learn-vault-agent-injector-clusterrole" is forbidden: User "174602363821-compute@developer.gserviceaccount.com" cannot delete resource "clusterroles" in API group "rbac.authorization.k8s.io" at the cluster scope: requires one of ["container.clusterRoles.delete"] permission(s).
│ 
│ 
╵



I'm working from a sandbox deployed via ACloudGuru, so the GCE sandbox might have some limiters, not sure if one of those is getting in the way, ( Previously, I did all the GCE tutorials with that sandbox succesfully) 

I'm going to try the other lab to deploy K8s with GCE, to see if I got the same issue.

And will also try this lab with my personal GCE account, 

I'll get back with the results.

**Comment by vodelerk** [comment]
got results, just tried with my GCE personal account, and I got the same results:

![image](https://user-images.githubusercontent.com/17457173/119066661-dccb8580-b9a5-11eb-9bb6-f3c83297c802.png)

no consul-server-0 or hashicorp-learn-vault-0 anywhere, in TFC everything is deployed as expected with no issue:

![image](https://user-images.githubusercontent.com/17457173/119066763-1c926d00-b9a6-11eb-850f-456716edb442.png)

I'm defining a user and pass in the k8s workspace, are you defining those or you leave them by default?

**Comment by im2nguyen** [comment]
Is your TFC organization just used for testing? If so, can you temporarily add me to it for debugging? `tu.nguyen@hashicorp.com`?

**Comment by vodelerk** [comment]
yes, this TFC org is just for testing, done my friend, invitation sent!

**Comment by im2nguyen** [comment]
There's something going on with the helm release. Even though it's been scheduled, it's not actually active on the cluster. 

I think this has to do with your user/RBAC permissions. I'm getting this error when I try to destroy or recreate the resource.

> Error: failed to create resource: clusterroles.rbac.authorization.k8s.io is forbidden: User "541600210082-compute@developer.gserviceaccount.com" cannot create resource "clusterroles" in API group "rbac.authorization.k8s.io" at the cluster scope: requires one of ["container.clusterRoles.create"] permission(s).

**Comment by im2nguyen** [comment]
To fix this, your GCP service account should have at least [Kubernetes Engine Developer role](https://cloud.google.com/iam/docs/understanding-roles#container.developer) to create the resources. 

Refer to this [GCP docs page](https://cloud.google.com/iam/docs/granting-changing-revoking-access) for instructions on how to do this 😄 

Please let me know if this works. If it does, we need to update the tutorial to include this role as a prereq

**Comment by vodelerk** [comment]
I assign that role to the service account that has the key to access, but I'm still getting: "cannot get resource "namespaces" in API group "" in the namespace "hashicorp-learn": requires one of ["container.namespaces.get"] permission(s)."

but that permission is contained in that role,

![image](https://user-images.githubusercontent.com/17457173/119074054-f1167f00-b9b3-11eb-9044-dea9ebdf8965.png)

![image](https://user-images.githubusercontent.com/17457173/119074211-3cc92880-b9b4-11eb-857c-9d89267eb97a.png)

**Comment by im2nguyen** [comment]
Does the `GOOGLE_CREDENTIALS` that you set as a TFC variable belong to that user? It seems like the keys are different 🤔 

The service account shows xxx082-`compute@developer.gserviceaccount.com`, while the member with the Kubernetes Engine Developer role is xxx082@`cloudservices.gserviceaccount.com`.

Granting xxx082-compute the K8s Engine Developer role should address this issue 😄

**Comment by vodelerk** [comment]
looks like the roles solved that issue btw, I might be sleepy but now, I'm trying to recreate the consul workspace, but because it was not deleted before, it got stuck with: 
 
Terraform v0.15.4
on linux_amd64
helm_release.consul[0]: Destroying... [id=hashicorp-learn-consul]
╷
│ Error: uninstall: Release not loaded: hashicorp-learn-consul: release: not found
│ 
│ 
╵


is there a way I can delete that TFC state or the only solution would be to delete that workspace and create it again?

not sure if its a stupid question or not at this point,

**Comment by im2nguyen** [comment]
Awesome! glad to hear that the roles solve the issue, will update the tutorial to reflect the roles requirement. Thank you for being patient while we debugged that 😄  (you can also remove me from the TFC organization)

Unfortunately, the only way to currently handle that is to delete the workspace then recreate it. We're working on fixing this workflow

**Comment by vodelerk** [comment]
yes, I can confirm, that solves the issue, but I had to add this other role: 

Kubernetes Engine Developer
GKE Hub Service Agent

consul
![image](https://user-images.githubusercontent.com/17457173/119081156-07770780-b9c1-11eb-90fa-79cd38961bf7.png)

vault
![image](https://user-images.githubusercontent.com/17457173/119081432-8cfab780-b9c1-11eb-96f8-b83b9da1c5d5.png)

everything working as expected! thank you very much!!!!!!!!! @im2nguyen 

one last thing, it would be really awesome to have a feature in TFC that allows you to duplicate workspaces and left them in a draft mode, like a baseline, if you guys have a wishlist for TFC features.

**Comment by im2nguyen** [comment]
That's great to hear @vodelerk !

If you want to, you can open a PR for this repo (remove `master_auth` from `google_container_cluster.engineering`), that way you get to contribute to the repo 😄  otherwise, I can update it

**Comment by vodelerk** [comment]
I will, let me get that PR ready.
